# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 01:51
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTaxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hour', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('reference', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CabRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('initial_address', models.CharField(default=b'initial_address', max_length=250)),
                ('final_address', models.CharField(default=b'final_address', max_length=250)),
                ('career_total', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('expires', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born_date', models.DateField(verbose_name=b'fecha de nacimiento')),
                ('phone', models.CharField(default=b'phone number', max_length=20)),
                ('home_address', models.CharField(max_length=150)),
                ('work_address', models.CharField(max_length=150)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('initial_address', models.CharField(max_length=250)),
                ('destination_address', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('reference', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(default=0.0, max_length=200)),
                ('longitude', models.CharField(default=0.0, max_length=200)),
                ('notification_id', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=True)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.ServiceType'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.Driver'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.Customer'),
        ),
        migrations.AddField(
            model_name='cabride',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.Customer'),
        ),
        migrations.AddField(
            model_name='cabride',
            name='driver',
            field=models.ForeignKey(blank=True, default=b'1', null=True, on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.Driver'),
        ),
        migrations.AddField(
            model_name='cabride',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.ServiceType'),
        ),
        migrations.AddField(
            model_name='booktaxi',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.Customer'),
        ),
        migrations.AddField(
            model_name='booktaxi',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.Driver'),
        ),
        migrations.AddField(
            model_name='booktaxi',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.ServiceType'),
        ),
    ]
