# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_amigo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='password',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
    ]
