# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_amigo', '0002_auto_20160517_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='driver',
            name='latitude',
            field=models.CharField(default=0.0, max_length=200),
        ),
        migrations.AddField(
            model_name='driver',
            name='longitude',
            field=models.CharField(default=0.0, max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AddField(
            model_name='history',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.Customer'),
        ),
        migrations.AddField(
            model_name='history',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.Driver'),
        ),
        migrations.AddField(
            model_name='coupons',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.Customer'),
        ),
    ]
