# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_amigo', '0003_auto_20160518_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupons',
            new_name='Coupon',
        ),
    ]
