# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi_amigo', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='typeservice',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='app_user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='app_user',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='avaliable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='notification_id',
            field=models.CharField(default='asdasdasdasdasdasd', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.ServiceType'),
        ),
        migrations.DeleteModel(
            name='Enterprise',
        ),
        migrations.DeleteModel(
            name='TypeService',
        ),
        migrations.AddField(
            model_name='driver',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.ServiceType'),
            preserve_default=False,
        ),
    ]
