# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_amigo', '0006_auto_20160620_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='avaliable',
            new_name='available',
        ),
    ]
