# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 00:29
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_amigo', '0007_auto_20160807_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=b'phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='career_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(default=b'1', on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.Driver'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_address',
            field=models.CharField(default=b'final_address', max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='initial_address',
            field=models.CharField(default=b'initial_address', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.Customer'),
        ),
    ]
