# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi_amigo', '0008_auto_20161012_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COUPON_VALUE', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('COUPON_NEW_USER_VALUE', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxi_amigo_coupon_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxi_amigo_coupon_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
