# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_amigo', '0008_auto_20160808_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCareer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hour', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('reference', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.Customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.Driver')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.ServiceType')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('initial_address', models.CharField(max_length=250)),
                ('destination_address', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('reference', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.Customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.Driver')),
            ],
        ),
    ]
