# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-27 03:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi_amigo', '0012_servicetype_type_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxi_amigo_taxi_driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxi_amigo_delivery_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='destination_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='destination_latitude',
            field=models.CharField(blank=True, default=0.0, max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='destination_longitude',
            field=models.CharField(blank=True, default=0.0, max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='initial_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='initial_latitude',
            field=models.CharField(blank=True, default=0.0, max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='initial_longitude',
            field=models.CharField(blank=True, default=0.0, max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='type_image',
            field=models.ImageField(upload_to=b'service_type'),
        ),
    ]
