# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-12 05:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_amigo', '0013_auto_20170526_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktaxi',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='booktaxi',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxi_amigo_booktaxi_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booktaxi',
            name='hour',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booktaxi',
            name='latitude',
            field=models.CharField(blank=True, default=0.0, max_length=200),
        ),
        migrations.AlterField(
            model_name='booktaxi',
            name='longitude',
            field=models.CharField(blank=True, default=0.0, max_length=200),
        ),
        migrations.AlterField(
            model_name='booktaxi',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='booktaxi',
            name='service_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='taxi_amigo.ServiceType'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
