# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='service_type',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
