# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-30 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_auto_20161008_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='player_id',
            field=models.CharField(default='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', max_length=200),
        ),
    ]
