# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-17 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_auto_20170130_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.CharField(blank=True, default=0.0, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.CharField(blank=True, default=0.0, max_length=200),
        ),
    ]
